BrainSwap/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('theswap.urls', namespace="theswap")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
]

theswap/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    url(r'^accounts/profile', views.profile, name='profile'),
    url(r'^accounts/connect/', views.connect, name='connect'),
    url(r'^accounts/messages',views.messages, name='messages'),
    url(r'^accounts/message', views.message),
    url(r'^accounts/inbox', views.getBoxes),
    url(r'^accounts/deleteMessage', views.deleteMessage),
    url(r'^accounts/readMessage', views.readMessage),
    url(r'^$', TemplateView.as_view(template_name="index.html"))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block head_title %}{% endblock %}</title>
    {% load staticfiles %}
    <!-- Bootstrap/Semantic & stylesheets-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.4/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.4/semantic.min.js"></script>
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <!-- Jquery -->
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.4.min.js"></script>
    <script src="{% static "js/semantic.min.js" %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head %}
    {% endblock %}
    <body>
      <div id="top-menu" class="ui large menu">
        <a class="header item" href="{{HHTP_HOST}}/">
          <img class="logo" src="{% static "img/brain.png" %}">
          BrainSwap
        </a>
        {% if user.is_authenticated %}
          <a class="header item" href="{% url 'theswap:connect' %}">
            Connect
            <i class="circular users icon"></i>
          </a>
          <a class="header item" href="{% url 'theswap:messages' %}">
            Messages
            {% if user.profile.unread_messages > 0 %}
            <i class="medium icons">
            <i class="mail icon"></i>
            <i class="corner icon"><div class="ui red huge header">{{ user.profile.unread_messages }}</div></i>
            </i>
            {% else %}
            <i class="medium icons">
            <i class="mail icon"></i>
            </i>
            {% endif %}
          </a>
        {% endif %}
        <div class="right menu">
          {% if user.is_anonymous %}
            <a href="{% url 'account_signup' %}" class="item">
              Sign up
            </a>
            <a href="{% url 'account_login' %}" class="item">
              Log in
            </a>
          {% endif %}
          {% if user.is_authenticated %}
            <div id="user" class="ui right dropdown browse item">
              {{ request.user.username }}
              <i class="circular user icon"></i>
              <div class="menu">
                <a class="item" href="{% url 'theswap:profile' %}">Edit profile</a>
                <a class="item" href="{% url 'account_logout' %}">Logout</a>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
      {% block content %}
      {% endblock %}
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      {% block scripts %}
        <script src="{% static "js/main.js" %}" type="text/javascript"></script>
      {% endblock %}
    </body>
  </html>

templates/connect.html
{% extends "base.html" %}
{% load staticfiles %}
{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>
    <script src="{% static "js/connect.js" %}" type="text/javascript"></script>
    <script src="{% static "js/connectModule.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
<div ng-app="connectApp" ng-controller="connectController">
        <div style="display:none">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        </div>
        <h1 class="ui header centered">Connect With Other Students</h1>
        <div class="ui container padded">
            <div class="ui grid">
                <div class="four wide column">
                    <div class="ui secondary vertical pointing menu">
                        <a class="item active" data-tab="recommended">
                            Recommended Matches
                        </a>
                        <a class="item" data-tab="get-help">
                            Find Help
                        </a>
                        <a class="item" data-tab="give-help">
                            Offer Help
                        </a>
                    </div>
                </div>
                <div class="twelve wide stretched column">
                    <div class="ui segment raised">
                        <div id="recommended"  onmouseover="disableBodyScroll();" onmouseout="enableBodyScroll();" class="ui tab active" data-tab="recommended">
                            {% for student in matches %}
                                <div class="ui segment padded ">
                                    <div class="ui equal width grid">
                                        <div class="column">
                                            <h3> <i class="ui circular user icon"></i>{{ student.username}}</h3>
                                        </div>
                                        <div class="column">
                                            <div data-name="{{student.username}}" data-value="{{student.id}}" class="ui right floated vertical animated button">
                                                <div class="hidden content">Message</div>
                                                <div class="visible content">
                                                    <i class="mail icon"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="ui accordion">
                                        <div class="title">
                                            <i class="dropdown icon"></i>
                                            Read Summary
                                        </div>
                                        <div class="content">
                                            {{ student.profile.summary }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="ui tab" data-tab="get-help">
                            <form id="get-connect" class="ui form">
                                <h4 class="ui dividing header">Information To Get Help</h4>
                                <div class="ui grid">
                                    <div class="eight wide column">
                                        <label>Find Help By Major</label>
                                        <select name="find-majors" class="getMajors ui fluid search dropdown" multiple="">
                                            {% for major in majors %}
                                                <option value={{major.id}}>{{ major.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="eight wide column">
                                        <label>Find Help By Subject</label>
                                        <select name="profs" class="profs ui fluid search dropdown" multiple="">
                                            {% for prof in profs %}
                                                <option value={{prof.id}}>{{prof.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="ui tab" data-tab="give-help">
                            <form id="give-connect" class="ui form">
                                <h4 class="ui dividing header">Information To Offer Help</h4>
                                <div class="ui grid">
                                    <div class="eight wide column">
                                        <label>Offer Help By Major</label>
                                        <select class="giveMajors ui fluid search dropdown" multiple="">
                                            {% for major in majors %}
                                                <option value={{major.id}}>{{ major.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="eight wide column">
                                        <label>Offer Help By Subject</label>
                                        <select class="defs ui fluid search dropdown" multiple="">
                                            {% for def in defs %}
                                                <option value={{def.id}}>{{def.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="twelve wide stretched column right floated">
                    {% verbatim %}
                    <div class="ui segment raised" id="results">
                        <div ng-if="connections.length < 1">
                        Use the above fields to search for students
                        </div>
                        <div ng-repeat="connect in connections" id="connect-results"  class="ui container padded">
                            <div class="ui segment padded margined ">
                                <div class="ui equal width grid">
                                    <div class="column">
                                        <h3> <i class="ui circular user icon"></i>
                                        {{ connect.name }}</h3>
                                    </div>
                                    <div class="column">
                                        <div ng-click="makeMessage(connect.id, connect.name)" class="ui right floated vertical animated button">
                                            <div class="hidden content">Message</div>
                                            <div class="visible content">
                                                <i class="mail icon"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="ui accordion">
                                    <div class="title">
                                        <i class="dropdown icon"></i>
                                        Read Summary
                                    </div>
                                    <div class="content">
                                        {{ connect.summary }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endverbatim %}
            </div>
        </div>
    </div>
    <div class="ui large modal">
        <div class="ui container">
            <div class="ui segment padded">
                <div class="ui form" action="{{HTTP_HOST}}/accounts/message/" method="post">
                    <div class="field">
                        <label id="message-title"></label>
                        <textarea id="message-body" rows="10"></textarea>
                    </div>
                    <input  type="hidden" id="recipient-id"></input>
                    <button id="message-send" class="ui button centered" >Send</button>
                </div>
                <div class="ui segment">
                    <p id="message-response"></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/email.html
<h3>{{ username }} wants to connect with you!</h3>
<div>
<h4>Message</h4>
<p>{{ message }}</p>
</div>
<p> Respond to this email to get in touch with them, or email back at {{ email }}</p>

templates/index.html
{% extends "base.html" %}
{% block content %}
  <h1 class="ui header centered">Welcome To The BrainSwap</h2>
  <div class="ui raised padded container ">
    <div class="segment">
      <div class="ui secondary pointing menu">
        <a class="active item" data-tab="about">
          About
        </a>
        <a class="item" data-tab="team">
          Team
        </a>
        <a class="item" data-tab="faq">
          FAQ
        </a>
      </div>
      <div class="ui centered grid">
        <div class="fourteen wide column">
          <div class="ui segment padded">
            <div class="ui tab active" data-tab="about">

              <p>
              <h4>BrainSwap is a platform for to help students connect locally for the purpose of academic collaboration. BrainSwap is not a market place for tutors, though we do not discourage development of professional tutoring relationships.
              </h4>
              </p>

            </div>
            <div class="ui tab" data-tab="team">
              <h1 class="ui header">Sam Hopkins
              <div class="sub header">Founder & Lead Engineer</div>
              </h1>
            </div>
            <div class="ui tab" data-tab="faq">
              <h2 class="ui header">Frequently asked questions</h2>
              <div class="ui list">
                <div class="item">
                  <div class="ui accordion">
                    <div class="title">
                      <i class="dropdown icon"></i>
                      How does this work
                    </div>
                    <div class="content">
                    <h4>
                      Simply specify in your profile subjects you would feel comfortable assisting other students with as well as subjects you need assistance with. Using this information along with your major(s) we can recommend students for you to contact. You are also able to search for students to assist you or for you to assist based on the aforementioned profile information.
                      </h4>
                    </div>
                  </div>
                </div>
                <div class="item">
                  <div class="ui accordion">
                    <div class="title">
                      <i class="dropdown icon"></i>
                      Is this service anonymous
                    </div>
                    <div class="content">
                    <h4>
                      Mostly. The only explicitly public information is your user name and summary. If you decide to contact another user they will receive your email as means of contacting you back. Information like profile classes can be inferred from matches, but it is never actually disclosed.
                      </h4>
                    </div>
                  </div>
                </div>
              <div class="item">
                 <div class="ui accordion">
                    <div class="title">
                      <i class="dropdown icon"></i>
                      Are there rules about charging money for assistance?
                    </div>
                    <div class="content">
                    <h4>
                      As stated in the about section, though BrainSwap is not necessarily a marketplace for paid tutors, we do not discourage users from establishing professional tutor relationships or otherwise.
                      </h4>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
$('.secondary.pointing.menu .item').tab();
</script>
{% endblock %}

templates/messages.html
{% extends "base.html" %}
{% load staticfiles %}
{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>
    <script src="{% static "js/module.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <div style="display:none">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    </div>
    <div class="ui container padded" ng-show="loaded" ng-app="messageApp" ng-controller='messageController'>
        <div class="ui grid ">
            <div class="six wide column">
                <div class="ui segment">
                    <div class="ui top attached tabular menu">
                        <a class="item active" data-tab="inbox"> Inbox</a>
                        <a class="item" data-tab="outbox"> Outbox</a>
                    </div>
                    <div class="ui bottom attached tab segment active boxes" data-tab="inbox">
                        {% verbatim %}
                        <div ng-if="inBox.length < 1">
                        No messages in inbox
                        </div>
                        <div class="ui list" ng-repeat='message in inBox track by $index'>
                            <div class="item">
                                <div class="ui segment mail" ng-class="{true: 'blue'}[message.read == false]">
                                    <div class="ui equal width grid">
                                        <div class="column">
                                            <div class="ui medium header person">
                                                From: {{ message.sender }}
                                            </div>
                                        </div>
                                        <div class="column">
                                            <i class="right floated check icon zoom" ng-click="deleteMessage(true, $index)"></i>
                                        </div>
                                    </div>
                                    <p class="content" ng-click="populateInboxMessage($index)">
                                        {{ message.content | limitTo:150}}{{message.content.length < 150 ? '' : '...'}}
                                    </p>
                                    <p>
                                        {{  message.created }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endverbatim %}
                </div>
                <div class="ui bottom attached tab segment boxes " data-tab="outbox">
                    {% verbatim %}
                    <div ng-if="outBox.length < 1">
                        No messages in outbox
                        </div>
                    <div class="ui list" ng-repeat="message in outBox track by $index">
                        <div class="item">
                            <div class="ui segment mail">
                                <div class="ui equal width grid">
                                    <div class="column">
                                        <div class="ui medium header person">
                                            To: {{ message.recipient }}
                                        </div>
                                    </div>
                                    <div class="column">
                                        <i class="right floated check icon zoom" ng-click="deleteMessage(false, $index)"></i>
                                    </div>
                                </div>
                                <p class="content" ng-click="populateOutboxMessage($index)">
                                    {{ message.content | limitTo:150}}{{message.content.length < 150 ? '' : '...'}}
                                </p>
                                <p>
                                    {{ message.created }}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endverbatim %}
            </div>
        </div>
    </div>
    <div  class="ten wide column" >
        <div class="ui segment" id="message-body">
            <div class="ui medium header">
            {% verbatim %}{{ title }}{% endverbatim %}
        </div>
        <p>
        {% verbatim %}{{ message }}{% endverbatim %}
    </p>
</div>
<button class="ui primary button" ng-click="reply = true; newMessage = ''; closeMessageText = 'Cancel'">
New Message
</button>
<div class="ui segment" id="response" ng-show="reply">
    <div class="ui form">
        <div class="ui equal width grid">
            <div class="column">
                <div class="ui small header">{% verbatim %}{{ 'To: ' + recipient_name}}{% endverbatim %}</div>
            </div>
            <div class="column">
                <i class="ui right floated remove icon zoom" ng-click="reply = false; sending = false"></i>
            </div>
        </div>

        <div class="field" >
            <textarea ng-model="newMessage"></textarea>
        </div>
        <button class="ui primary button" ng-disabled='sending' ng-click="sendMessage(); sending = true">
        <i class="ui send icon"></i>
        </button>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

    <h1 class="ui header centered">{{ request.user.username }}'s Profile</h2>
    <div class="ui raised padded container ">
    <form class="ui large form" method="post">
    {% csrf_token %}
    <div class="ui segment">
        {{ form.summary }}
    </div>

    <div class="ui segment stacked">
    <div class="ui three column very  grid">

        <div class="column">
            <div class="ui pointing below label large">Your Major(s)</div>
            {{ form.majors}}
        </div>

        <div class="column">
             <div class="ui pointing below label large">Subjects You Can Offer Help With</div>
            {{form.profs}}
        </div>

         <div class="column">
         <div class="ui pointing below label large">Subjects You Need Help With</div>
            {{form.defs}}
        </div>
        </div>
        <div class="ui horizontal divider">
        <div class="ui fluid large customblue submit button"><input type="submit"/></div>
        </div>
        </div>
        </form>
        </div>
        <script>
        $('.ui.dropdown').dropdown();
    </script>
{% endblock %}

templates/recommended.html
{% extends "base.html" %}
{% load staticfiles %}
{% block scripts %}
    <script src="{% static "js/connect.js" %}" type="text/javascript"></script>
{% endblock %}
{% block content %}
    <div class="ui container">
        <h1 class="ui centered header">Recommended Contacts </h1>
        <div class="ui segment padded">
            {% for student in matches %}
                <div class="ui segment padded ">
                    <div class="ui equal width grid">
                        <div class="column">
                            <h3> <i class="ui circular user icon"></i>{{ student.username}}</h3>
                        </div>
                        <div class="column">
                            <div value="{{student.id}}" class="ui right floated vertical animated button">
                                <div class="hidden content">Message</div>
                                <div class="visible content">
                                    <i class="mail icon"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}